### ISSUE TITLE
Coloring Numbers in Symbols???

### ISSUE THREAD

**Issue by cjmoorejr** [ironsheep/P2-vscode-extensions#1]
What's the consensus here?
![2021-02-17-VSC-Spin2-Extension](https://user-images.githubusercontent.com/36820917/108283331-b3058700-7148-11eb-8944-1a66af0f03a1.PNG)
Should the numbers remain white like the rest of the symbol (i.e. MS-001 & US-001?

**Comment by ironsheep** [comment]
Yes, this is c a BUG which I still haven't figured out how to fix.  But I will!

Thanks for reporting this!

**Comment by ironsheep** [comment]
Fixed in latest commit.  Fixes appear in v0.3.0 and later.
