### ISSUE TITLE
Global labels in outline should be sub-items of the DAT block they are in

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-extensions#13]
Title. This is possible, here's the C++ extension doing it:
![image](https://user-images.githubusercontent.com/6944842/210798119-48b77db8-4949-45c0-a3cd-6a515a803287.png)

**Comment by ironsheep** [comment]
Fixes committed, Will appear in v1.8.4 and later.

**Comment by ironsheep** [comment]
Oh, and thank you.  This is a fun and more importantly useful suggestion!
