### ISSUE TITLE
OBJ include without space after colon highlights incorrectly

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-extensions#15]
![image](https://user-images.githubusercontent.com/6944842/216789294-dc110756-402e-426e-ba17-a6157b624474.png)

**Comment by ironsheep** [comment]
I'll fix it, good catch.  
(what are you conserving on white space?) ;-)

**Comment by ironsheep** [comment]
ok, found that the underlying syntax parse is correct. Further semantic processing is breaking it.  
The fix will appear in the next release.

**Comment by ironsheep** [comment]
Changes committed. Fixes appear in v1.8.7 and later.
