### ISSUE TITLE
Freeze when opening certain files

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-extensions#24]
### and have you...

- [X] I updated to the latest spin2 version available
- [X] I have restarted VSCode and the problem still exists

### Version of Spin2 VScode Extension with the issue

whatever is current

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Hardware, Operating System, Operating System version, VSCode version

Hardware: IRQsomeSoftware(TM) shitbox(TM) Mk.I
OS Ver: Kubuntu 23.04
VSCode Ver: VSCodium 1.82.2

### Description of problem

When opening the P2 Spin Hexagon top source file (attached `hexagon.spin`) with the extension enabled, the VSC editor freezes or becomes very slow (controls such as switching to a different tab function as normal). Without the extension loaded, this doesn't happen, but it immediately starts freezing again when enabling the extension.
[hexagon-2023-09-24.zip](https://github.com/ironsheep/P2-vscode-extensions/files/12709283/hexagon-2023-09-24.zip)

**Comment by ironsheep** [comment]
I'll make sure this is fixed in the first LSP release (if I don't do a non-LSP release before then)

**Comment by ironsheep** [comment]
Hmm... seeing spin code in .spin2 files and  spin2 in .spin  files. They have a lot of red because of incorrect language in the given file, BUT I'm not seeing any lockups.

**hexagon_sdda.spin2** (Spin V2 language) contains spin (v1) object constant uses:  Ex: 

```
line(61) erc:=\fat.FATEngineStart(plat#SD_DO,plat#SD_CLK,plat#SD_DI,plat#SD_SELECT,false)
```

**hexagon.spin** (Spin V1 language) contains spin2 method uses: Ex:

```
line(333):   wrpin(plat#CONTROLACC_BASEPIN+4+(3<<6),P_NORMAL|P_LOW_150K|P_HIGH_FLOAT)
line(334):  pinl(plat#CONTROLACC_BASEPIN+4+(3<<6))
```

**platform.spin** (Spin V1 language) contains non spin(or spin2) object declaration: Ex:

```spin2
line(48): OBJ video = "p2videodrv.spin2"
```
_This should be a colon vs. an "=" separator._

Wow, and the Syntax parser is not coloring the **platform.spin** file.  This I'm looking into...  
Um, NOPE, never mind. This appears to be due to the syntax parser being unable to handle the undeclared first section of CON. This is a known bug.

**Comment by ironsheep** [comment]
I have no plans to support mixed p1 and p2 syntax in the same file.  So I'm not sure I can do anything about these.

What do you think should be fixed if there's no lockup?

I am adding error reporting for object declarations that I can't parse!

**Comment by Wuerfel21** [comment]
The = style object declaration is a flexspin feature. It means something special (reference class but don't instantiate an instance - you can use the subscript operator to then access an instance through a pointer - also good if you just need to reference constants)

**Comment by ironsheep** [comment]
**sdspi_with_audio.spin2** (Spin v2 language) missing org directives at start of DAT (required to enter pasm parser.) ex:

```spin2
dat 'do_init     'RJA disabled smartpins
do_init

                getbyte pinDO,          arg1_in,    #0
                getbyte pinCLK,         arg1_in,    #1
```

The parser fails to handle this correctly as it is not data declarations so it flags lots of random bits.

Also found a missing comment "'" at:

```spin2
con  smartpin_constants
```

so it flagged **smartpin_constants** as a constant expression missing the '=' assignment part.

**Comment by ironsheep** [comment]
FOUND: **VJET_p2beta_displaylist.spin2** (Spin V2 language) 1 line is causing the parser crash:

```spin2
PUB line_polygon(polyptr,vcount,width,colors) | i,px,py

  px := long[polyptr][(vcount<<1)-2]
  py := long[polyptr][(vcount<<1)-1]
  repeat i from 0 to vcount-1
     line(px,py,px := long[polyptr][(i<<1)],py := long[polyptr][(i<<1)+1],width,colors)
```

The last line causes a crash.  It shouldn't happen.

Hrmf...  not a crash per see, my new parser was mis-tokenizing the statement then couldn't find the mashed parts. so generating errors with bad char offsets.

So, let me understand this code.

I think you are implying this:

```spin2
PUB line_polygonSimple(polyptr,vcount,width,colors) | i, px, py, px2, py2

  px := long[polyptr][(vcount<<1)-2]
  py := long[polyptr][(vcount<<1)-1]
  repeat i from 0 to vcount-1
    px2 := long[polyptr][(i<<1)]
    py2 := long[polyptr][(i<<1)+1]
    line(px,py,px2,py2,width,colors) 
```

...with you intending to save from allocating two more variables but counting on the compiler's order of operations to keep the old and new px and py values correct.

Am I right?

**Comment by Wuerfel21** [comment]
yes, that's roughly how that works. It wants to draw lines between points, so each point needs to be used twice. The previous point is stored in px/py, which is updated in the same statement where it just got used.

**Comment by Wuerfel21** [comment]
Appears to be fixed in current version
