### ISSUE TITLE
Show opening comment for DAT/CON sections

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-extensions#4]
As is, CON/DAT just show up in the file outline as "DAT" and "CON". I usually place a comment on those first lines when I have a lot of DAT sections to make it easy to find the one I want in Propeller Tool. That should probably go on the outline.

```spin
CON ' Constants relating to.. something
  
  PANCAKES = 5

DAT ' Pancake flipping assembly code

  org 0
  [...]
```

**Comment by ironsheep** [comment]
@Wuerfel2, an Excellent request!  (Meaning this is already supported!)

When people were first discussing this, we adopted a more visual form of a comment to cause the comment to appear in the outline (and to look more unique in the code):

![Screen Shot 2022-02-20 at 18 45 25](https://user-images.githubusercontent.com/540005/154875866-3fd8ce87-b0e6-434b-8e32-fd511f798085.png)

If you change from **single-quote** to **single braces** the comment will appear in the outline as you are requesting.

I reviewed the project docs and found that use of '{ comment }' is shown in the project [README.md](https://github.com/ironsheep/P2-vscode-extensions/tree/main/spin2#feature-code-outline) in the section entitled "**Feature: Code Outline**", on the [MarketPlace:spin2 web page](https://marketplace.visualstudio.com/items?itemName=IronSheepProductionsLLC.spin2) and in VSCode when you click on the extension to show its details under the same heading in all cases.

Maybe I should state this in those locations more clearly?

**Comment by Wuerfel21** [comment]
Enlightening. Line comment should definitely be parsed, too.

**Comment by ironsheep** [comment]
@Wuerfel21 added single quote comment support to outline parser.  Changes will appear in v1.3.6 and later.

**Comment by ironsheep** [comment]
Fixed version released.  Enjoy!

**Comment by Wuerfel21** [comment]
:heart: 

![image](https://user-images.githubusercontent.com/6944842/164993192-630da85c-35cc-4005-8643-beb5db3788d7.png)
