### ISSUE TITLE
Missing X_4P_4DAC1_WFBYTE symbol

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-extensions#6]
**Checklist:**

- [x] I updated to the latest spin2 version available
- [ ] I have restarted VSCode and the problem still exists

**Version of Spin2 Extension with the issue:** Current

**Last working version (if known):**

**Hardware, Operating System, VSCode version:** Does it really matter?

**Description of problem:**

![image](https://user-images.githubusercontent.com/6944842/174436683-c9b68af5-2300-44cd-8524-b6109ba58331.png)

**Comment by ironsheep** [comment]
@Wuerfel21 (as long as I'm fixing things... "should have checked before releasing last, sigh") I thought i'd find and fix this too.  Thanks for reporting this.  It turns out that the symbol was known (sort of) it was internally spelled badly.

**Comment by ironsheep** [comment]
repaired. Fixes avail in v1.3.9 and later.

**Comment by Wuerfel21** [comment]
Speaking of, what came of the whole "regex debug parsing" thing?

I did some research then and figured that matching balanced brace sequences is impossible with regex....
But not impossible with the oniguruma engine that VSC uses, which allows for recursive patterns...

**Comment by ironsheep** [comment]
I still need/want to make it better.
We should setup zoom call... I'm interested to hear what you've found out.

**Comment by Wuerfel21** [comment]
Sure, just shoot me a mail when you have time
