### ISSUE TITLE
Caret/xor operator is treated as part of identifier

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-extensions#7]
**Checklist:**

- [x] I updated to the latest spin2 version available
- [ ] I have restarted VSCode and the problem still exists

**Description of problem:**
Caret/xor operator is treated as part of identifier. This doesn't happen with plus/minus/star/etc, but I haven't exhaustively tested all operators.

![image](https://user-images.githubusercontent.com/6944842/183469243-5d781e01-27a8-4611-8bb8-3c707a5f6c16.png)

**Additional information:**  (please attach your source file (.spin2) exhibiting the problem you are describing.)
https://github.com/IRQsome/NeoYume/blob/2a764eb5ea9c3bab88325db58d6a07bdc712fae7/neoyume_lower.spin2#L3103

**Comment by ironsheep** [comment]
@Wuerfel21 on it!   Good find.

**Comment by ironsheep** [comment]
@Wuerfel21 you should have a new extension version with the fixes. It's been uploaded to the Marketplace.
Thanks again for reporting this!
