### ISSUE TITLE
enumeration coloring

### ISSUE THREAD

**Issue by dnalorp** [ironsheep/P2-vscode-extensions#8]
Wrong colors with assignment in enumeration:
![image](https://user-images.githubusercontent.com/13612108/185747856-d3b94571-ced6-417f-bc4c-7c90542bded3.png)

**Comment by ironsheep** [comment]
Confirmed, will fix in upcoming release...

**Comment by ironsheep** [comment]
Fixed, Changes appear in v1.4.1 and later.
